# Gunrock/Essentials Ubuntu Workflow
name: Ubuntu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master and dev branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  ARCHITECTURES: 75
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        
    # https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
    if: "!contains(github.event.commits[0].message, '[skip ubuntu]')"
    runs-on: ${{matrix.os}}

    steps:
      - name: Get more space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      # Fetch CUDA toolkit using Jimver/cuda-toolkit
      - name: Fetch CUDA toolkit
        uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
          linux-local-args: '["--toolkit"]'

      - name: Check nvcc version
        run: nvcc -V
        
      - uses: actions/checkout@v3
        
      - name: Configure cmake
        run: cmake -B ${{github.workspace}}/build -DESSENTIALS_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DESSENTIALS_BUILD_BENCHMARKS=ON -DCMAKE_CUDA_ARCHITECTURES=${{env.ARCHITECTURES}}
        
      - name: Build all applications
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
